### ISSUE TITLE
Inputting the party id should allow to join

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/songvoter-frontend#5]
That should work
![Screenshot_2023-10-05-21-34-46-19_1416244010c1bab15ab2a2a026c2faa2.jpg](https://github.com/Coflnet/songvoter-frontend/assets/16632490/f49b9b19-f58a-4027-872a-7545a6b049d6)

**Comment by matthias-luger** [comment]
@Ekwav Are party IDs always 6 characters long?

**Comment by Ekwav** [comment]
> @Ekwav Are party IDs always 6 characters long?

6 or more characters 
its created with https://github.com/ullmark/hashids.net
